# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-31 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_image_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='message',
            field=models.CharField(blank=True, default='Hey', max_length=80),
        ),
    ]
