# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-30 18:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0002_auto_20200212_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_date',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.RemoveField(
            model_name='image',
            name='upload_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profilePic',
        ),
        migrations.AddField(
            model_name='image',
            name='my_image',
            field=models.ImageField(default='gallery/image.jpg', upload_to='gallery/'),
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='Armies', max_length=150),
        ),
        migrations.AddField(
            model_name='image',
            name='time_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='profile/image.jpg', null=True, upload_to='profile/'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
