# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-30 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0003_auto_20200530_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='message',
            field=models.TextField(default='Hey there.'),
        ),
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.ForeignKey(default='Looking good', on_delete=django.db.models.deletion.CASCADE, to='gram.Comment'),
        ),
    ]
