# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-30 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0009_remove_image_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.ManyToManyField(to='gram.Comment'),
        ),
    ]
