# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-30 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0013_remove_image_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='uname',
            field=models.CharField(default='Yensantos', max_length=80),
        ),
    ]
