# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-30 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0014_profile_uname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='profile/image.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
