# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-31 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0015_auto_20200531_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='profile/image.jpg', upload_to='profile_pics/'),
        ),
    ]
