# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-31 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0016_auto_20200531_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(upload_to='profile_pics/'),
        ),
    ]
