# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-31 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0017_auto_20200531_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='my_image',
            field=models.ImageField(upload_to='gallery/'),
        ),
    ]
