# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-31 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0018_auto_20200531_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uname',
            field=models.CharField(default='Nimo', max_length=80),
        ),
    ]
